### ISSUE TITLE
Erro da pipeline - Arquivo não encontrado

### ISSUE THREAD

**Issue by PauloGoncalvesBH** [doamaral/api-testing-cucumber-supertest-chai#1]
@doamaral pelo que constatei, o nome do arquivo está como `CardComponent`, enquanto no _dashboardPage_ está procurando por `cardComponent`. (C do card está minúsculo)

https://github.com/doamaral/api-testing-cucumber/blob/b1445595c2bb924603f7a0c50b70ed6727520d56/page-objects/dashboardPage.js#L1

Pra funcionar basta corrigir o nome do arquivo pra `cardComponent`, seguindo o padrão dos outros arquivos.

**Comment by doamaral** [comment]
![image](https://user-images.githubusercontent.com/7451330/94953657-4a31b100-04be-11eb-8090-2d7b0f06f156.png)

No editor está com "c" minusculo.

**Comment by doamaral** [comment]
@PauloGoncalvesBH Muitíssimo obrigado.
